### PR TITLE
logging initialized early enough to display all intended log messages

### LINKED ISSUE #106: [BUG] Properly notify users of bad certs
**Describe the bug**
When scanning a site that doesn't have a valid cert, the error message doesn't let the user know that the problem is certs.  Instead, all that's shown is that ferox can't connect

**To Reproduce**
1. scan a site with an invalid cert
2. see `ERROR heuristics::connectivity_test Could not connect to any target provided`

**Expected behavior**
I expect a clear message notifying the user that the certificate is invalid

**Environment (please complete the following information):**
 - feroxbuster version: v1.4.0

**Additional context**
Thanks to @Decap1tator for pointing out the issue

### PR DESCRIPTION
**Pull request by epi052**
closes #106 

## Branching checklist
- [x] There is an issue associated with your PR (bug, feature, etc.. if not, create one)
- [x] Your PR description references the associated issue (i.e. fixes #123)
- [x] Code is in its own branch
- [x] Branch name is related to the PR contents
- [x] PR targets master

## Static analysis checks
- [x] All rust files are formatted using `cargo fmt`
- [x] All `clippy` checks pass when running `cargo clippy --all-targets --all-features -- -D warnings -A clippy::unnecessary_unwrap`
- [x] All existing tests pass

## Documentation
- [x] New code is documented using [doc comments](https://doc.rust-lang.org/stable/rust-by-example/meta/doc.html)
- [x] Documentation about your PR is included in the README, as needed

## Additional Tests
- [x] New code is unit tested
- [x] New code is integration tested, as needed
- [x] New tests pass

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -111,13 +105,8 @@ async fn scan(
...
     if words.len() == 0 {
-        eprintln!(
-            "{} {} Did not find any words in {}",
-            status_colorizer("ERROR"),
-            module_colorizer("main::scan"),
-            CONFIGURATION.wordlist
-        );
-        process::exit(1);
+        eprintln!("Did not find any words in {}", CONFIGURATION.wordlist);
+        process::exit(1); // todo cleanup?
```
Comment (epi052) [inline src/main.rs:109]: comment lint

File: src/main.rs [hunk 2]
```diff
@@ -111,13 +105,8 @@ async fn scan(
...
 
     if words.len() == 0 {
-        eprintln!(
-            "{} {} Did not find any words in {}",
-            status_colorizer("ERROR"),
-            module_colorizer("main::scan"),
-            CONFIGURATION.wordlist
-        );
-        process::exit(1);
+        eprintln!("Did not find any words in {}", CONFIGURATION.wordlist);
```
Comment (epi052) [inline src/main.rs:108]: should probably use feroxprint

File: src/main.rs [hunk 3]
```diff
@@ -165,12 +154,22 @@ async fn get_targets() -> FeroxResult<Vec<String>> {
     Ok(targets)
 }
 
-#[tokio::main]
-async fn main() {
-    // setup logging based on the number of -v's used
-    logger::initialize(CONFIGURATION.verbosity);
-
-    // can't trace main until after logger is initialized
+/// todo doc
```
Comment (epi052) [inline src/main.rs:157]: add doc

File: src/main.rs [hunk 4]
```diff
@@ -212,15 +203,40 @@ async fn main() {
...
+        }
     };
 
-    // manually drop tx in order for the rx task's while loops to eval to false
+    clean_up(tx_term, term_handle, tx_file, file_handle, save_output).await;
+
+    log::trace!("exit: main");
+}
+
+/// todo doc
```
Comment (epi052) [inline src/main.rs:231]: add doc

File: src/main.rs [hunk 5]
```diff
@@ -212,15 +203,40 @@ async fn main() {
...
+async fn clean_up(
```
Comment (epi052) [inline src/main.rs:232]: add trace

File: src/scanner.rs [hunk 6]
```diff
@@ -619,8 +619,6 @@ pub async fn scan_url(
     progress_bar.reset_elapsed();
 
     if CALL_COUNT.load(Ordering::Relaxed) == 0 {
-        // join can only be called once, otherwise it causes the thread to panic
-        tokio::task::spawn_blocking(move || PROGRESS_BAR.join().unwrap());
         CALL_COUNT.fetch_add(1, Ordering::Relaxed);
 
         // this protection around join also allows us to add the first scanned url to SCANNED_URLS
```
Comment (epi052) [inline src/scanner.rs:624]: fix comment
